### PR TITLE
Feature/share trip

### PR DESCRIPTION
**Pull request by EdmanJohan**
This feature enables the possibility to share a trip via the 'Android Easy Share' action in an easily readable text-format.

Feedback on the output-format is welcome. **(RouteDetailActivity -> Line 389...)**

### CODE REVIEW

**Comment by EdmanJohan** [comment]
Issue with sharing trip if walking is involved.

Linked issue: https://github.com/Team-Eight/sthlm-commuter/issues/8#issue-317657732

**Comment by EdmanJohan** [comment]
Resolved #8 as of commit https://github.com/Team-Eight/sthlm-commuter/commit/8c291247bf11ff7ddc427c4fed1b3e79265c7ae6 , refactoring still needed.

**Review by a-ehlert — APPROVED** [review]
Works well looks alright
Maybe the button could be bigger and a different color (slightly brighter) to match the rest of the GUI

**Review by OskarHahr — APPROVED** [review]
Functionality works well

**Pull request merged**
